version: '3.8'

services:
  postgres:
    container_name: postgres-prod
    image: postgres
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      syllabus-network:


  backend:
    depends_on: [ postgres ]
    container_name: backend-prod
    image: backend-prod
    build:
      context: ../backend
      dockerfile: ../backend/Dockerfile-prod
    ports:
      - "10461:8080"
    networks:
      syllabus-network:


  frontend:
    container_name: frontend-prod
    image: frontend-prod
    build:
      context: ../frontend
      dockerfile: ../frontend/Dockerfile-prod
    ports:
      - "20461:4200"
    networks:
      syllabus-network:

volumes:
  postgres:

networks:
  syllabus-network: { }


